import type { JdSample } from "./jdSamples";

// 从用户提供的真实字节 JD 批次中抽出的短结构化风格样本。
// 保留职责/要求的写法颗粒度，不保留完整 JD 原文；用于 few-shot 风格参考。
export const BUILTIN_JD_STYLE_SAMPLES: JdSample[] = [
  {
    title: "大模型算法工程师-Data",
    position_id: "A165230A",
    location: "北京",
    recruit_type: "社招",
    job_family: "算法",
    category: "研发 - 算法",
    team_intro: "",
    responsibilities: [
      "主导大模型整体研发规划，结合行业特点与业务需求制定微调、对齐、部署等技术方案",
      "负责语料、知识图谱的收集、清洗、标注与优化，构建高质量行业训练数据集",
      "负责大模型后训练与优化，设计并实施 CPT、SFT、RLHF/RLAIF 等后训练流程",
      "构建垂类领域模型评测体系和评估指标，建立人机协同评估机制",
    ],
    requirements: [
      "本科及以上学历，计算机、人工智能、数学等相关专业，有大模型研发相关经验",
      "精通持续预训练、微调、蒸馏等技术，熟悉主流大模型框架",
      "具备扎实的机器学习、深度学习、NLP 基础，了解 Transformer、MoE 等底层原理",
      "熟悉至少一个垂类行业业务逻辑，能将行业知识与大模型技术深度结合",
    ],
    bonus_items: ["有明确模型落地案例者优先", "有模型工程化落地经验者优先"],
    keywords: ["大模型", "SFT", "RLHF", "LLM"],
    raw: "",
  },
  {
    title: "AI产品经理-抖音电商",
    position_id: "A175492A",
    location: "上海",
    recruit_type: "社招",
    job_family: "产品",
    category: "产品 - 产品经理",
    team_intro: "",
    responsibilities: [
      "负责抖音电商 AI 产品，探索 AI+电商的全新购物模式和交易体验",
      "协同算法、技术、运营团队，通过数据驱动优化，将人工运营经验转化为 AI 可落地策略",
      "跟随业务从 10 到 100 的突破，积累 AI 产品与电商的复合能力",
    ],
    requirements: [
      "对 AI 产品有深入了解和充分实践经验，保持对相关领域的学习和探索",
      "对数据敏感，能从业务现状和数据结果之间挖掘机会点并推动策略落地",
      "沟通表达能力好，强执行力，自驱力强，面对挑战有创新思路和结果导向意识",
    ],
    bonus_items: [],
    keywords: ["电商", "AI", "数据分析"],
    raw: "",
  },
  {
    title: "AI产品运营（智能助手）-抖音生活服务",
    position_id: "A150642A",
    location: "北京",
    recruit_type: "校招",
    job_family: "运营",
    category: "运营 - 产品运营",
    team_intro: "",
    responsibilities: [
      "负责智能客服产品运营，完善大模型知识和技能覆盖",
      "建立并执行线上质量监控机制，定位并分析问答负面案例，推动问题闭环解决",
      "建设问题标签和准确率统计体系，持续优化人工+机器标注双链路模式",
    ],
    requirements: [
      "具备互联网产品运营经验，有 AI 助手、智能问答工具运营经验者优先",
      "学习能力强，对 AI 技术及应用有浓厚兴趣，能结合业务场景提出产品优化方向",
      "具备较强的问题分析与解决能力，能独立完成问题收集、调研分析、体系搭建并推动落地",
    ],
    bonus_items: ["有 AI 助手、智能问答工具运营经验者优先"],
    keywords: ["运营", "AI", "智能助手"],
    raw: "",
  },
  {
    title: "数据分析实习生-抖音",
    position_id: "A15389",
    location: "北京",
    recruit_type: "转正实习",
    job_family: "数据分析",
    category: "产品 - 数据分析",
    team_intro: "",
    responsibilities: [
      "负责抖音业务的数据分析工作，覆盖内容、增长、变现、作者生态等多个业务模块",
      "结合业务目标洞察业务现状及问题，给出可落地的产品/运营优化方案",
      "负责 A/B 实验设计与分析、产品优化效果评估、运营策略分析评估和核心指标异动分析",
      "围绕业务目标展开专题分析，描述业务现状、洞察问题和机会点，并推动策略落地",
    ],
    requirements: [
      "2027 届本科及以上学历在读，数学、统计学、计算机相关专业优先",
      "逻辑清晰，对数据敏感，能发掘业务细节和数据之间的联系并通过指标推动优化",
      "精通 SQL，熟练使用 R/Python 进行数据分析、挖掘，掌握 Tableau 等 BI 工具尤佳",
    ],
    bonus_items: ["有视频行业数据分析实习经验、一线产品或运营业务优化经验者优先"],
    keywords: ["数据分析", "SQL", "Python", "A/B"],
    raw: "",
  },
  {
    title: "AI搜索算法实习生-Seed大模型人才实习",
    position_id: "A91211",
    location: "杭州",
    recruit_type: "日常实习",
    job_family: "算法",
    category: "研发 - 算法",
    team_intro: "",
    responsibilities: [
      "基于 AI 建设下一代搜索引擎，并服务于 AI Agents",
      "覆盖全网搜索、视频搜索、商品搜索、本地搜索、图片搜索、视觉搜索、结构化检索等场景",
      "基于 LLM/VLM 突破搜索排序、召回、内容理解、个性化等任务",
    ],
    requirements: [
      "本科及以上学历在读，计算机、人工智能等相关专业优先",
      "优秀的代码能力、数据结构和基础算法功底，熟练掌握 C++ 或 Python",
      "熟悉深度学习算法，有一定算法应用经验和出色的技术判断能力",
      "出色的数据和问题分析能力，对新问题能够独立探索解决方案",
    ],
    bonus_items: ["有 ACM/ICPC 等比赛获奖、顶会论文或顶级开源项目经验者优先"],
    keywords: ["搜索", "LLM", "VLM", "Agent"],
    raw: "",
  },
];
